server:
  port: 8080

spring:
  mail:
    host:
    port:
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  security:
    user:
      name: admin
      password: passw@rd

aws:
  upload-limit: 5
  region:
  key:
  secret:
  dynamo-db:
    amazonDBEndpoint:
  s3UploadBucketName: mdtupload
