server:
  port: 5000

spring:
  mail:
    host:
    port:
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  security:
    jwt:
      secret:
    user:
      name:
      password: passw@rd


aws:
  upload-limit: 5
  region: ap-southeast-2
  key:
  secret:
  dynamo-db:
    amazonDBEndpoint: 
  s3UploadBucketName: